"""Command Safety Firewall.

The single, mandatory boundary between application logic and OmniSwitch SSH sessions. Nothing
can be sent to a switch unless it was generated by :mod:`app.security.firewall` from the
authoritative policy in :mod:`app.security.policy`. See docs/SECURITY_FIREWALL.md.
"""
