"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 19:06:08.955912
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import app.db.base


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=48), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('target_label', sa.String(length=255), nullable=False),
    sa.Column('mac', sa.String(length=12), nullable=False),
    sa.Column('switch_name', sa.String(length=128), nullable=False),
    sa.Column('port', sa.String(length=32), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_ts'), ['ts'], unique=False)

    op.create_table('command_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('builtin', sa.Boolean(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_command_profiles')),
    sa.UniqueConstraint('key', name=op.f('uq_command_profiles_key'))
    )
    op.create_table('credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_encrypted', sa.Text(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credentials')),
    sa.UniqueConstraint('name', name=op.f('uq_credentials_name'))
    )
    op.create_table('strategy_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_key', sa.String(length=32), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('version_prefix', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=False),
    sa.Column('approved_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_approvals')),
    sa.UniqueConstraint('profile_key', 'strategy', 'version_prefix', name=op.f('uq_strategy_approvals_profile_key'))
    )
    op.create_table('system_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_system_settings'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('mac_searches',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('mac', sa.String(length=12), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('total_switches', sa.Integer(), nullable=False),
    sa.Column('checked', sa.Integer(), nullable=False),
    sa.Column('found_count', sa.Integer(), nullable=False),
    sa.Column('failed_count', sa.Integer(), nullable=False),
    sa.Column('timeout_count', sa.Integer(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_mac_searches_requested_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mac_searches'))
    )
    with op.batch_alter_table('mac_searches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mac_searches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_mac_searches_mac'), ['mac'], unique=False)

    op.create_table('switches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('host', sa.String(length=255), nullable=False),
    sa.Column('ssh_port', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('aos_version', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=True),
    sa.Column('profile_key', sa.String(length=32), nullable=False),
    sa.Column('transport', sa.String(length=16), nullable=False),
    sa.Column('host_key', sa.Text(), nullable=False),
    sa.Column('host_key_fingerprint', sa.String(length=128), nullable=False),
    sa.Column('legacy_ssh_algorithms', sa.Boolean(), nullable=False),
    sa.Column('uplink_ports', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('last_check_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['credential_id'], ['credentials.id'], name=op.f('fk_switches_credential_id_credentials'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_switches'))
    )
    with op.batch_alter_table('switches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_switches_name'), ['name'], unique=True)

    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('csrf_token', sa.String(length=64), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions'))
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('mac_search_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=True),
    sa.Column('switch_name', sa.String(length=128), nullable=False),
    sa.Column('switch_host', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('aos_version', sa.String(length=64), nullable=False),
    sa.Column('profile_key', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('port', sa.String(length=32), nullable=False),
    sa.Column('interface_raw', sa.String(length=64), nullable=False),
    sa.Column('is_linkagg', sa.Boolean(), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('mac_type', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('port_details', sa.JSON(), nullable=False),
    sa.Column('vlans', sa.JSON(), nullable=False),
    sa.Column('tagged_vlans', sa.JSON(), nullable=False),
    sa.Column('untagged_vlan', sa.Integer(), nullable=True),
    sa.Column('lldp', sa.JSON(), nullable=False),
    sa.Column('mac_count_on_port', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('classification_confidence', sa.String(length=8), nullable=False),
    sa.Column('classification_score', sa.Float(), nullable=True),
    sa.Column('classification_reasons', sa.JSON(), nullable=False),
    sa.Column('commands_executed', sa.JSON(), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['mac_searches.id'], name=op.f('fk_mac_search_results_search_id_mac_searches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['switch_id'], ['switches.id'], name=op.f('fk_mac_search_results_switch_id_switches'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mac_search_results'))
    )
    with op.batch_alter_table('mac_search_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mac_search_results_search_id'), ['search_id'], unique=False)

    op.create_table('mac_sightings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.String(length=12), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=True),
    sa.Column('switch_name', sa.String(length=128), nullable=False),
    sa.Column('port', sa.String(length=32), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('search_id', sa.String(length=36), nullable=True),
    sa.Column('seen_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['search_id'], ['mac_searches.id'], name=op.f('fk_mac_sightings_search_id_mac_searches'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['switch_id'], ['switches.id'], name=op.f('fk_mac_sightings_switch_id_switches'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mac_sightings'))
    )
    with op.batch_alter_table('mac_sightings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_mac_sightings_mac'), ['mac'], unique=False)
        batch_op.create_index(batch_op.f('ix_mac_sightings_seen_at'), ['seen_at'], unique=False)

    op.create_table('port_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_token', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('method', sa.String(length=16), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('profile_key', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=True),
    sa.Column('switch_name', sa.String(length=128), nullable=False),
    sa.Column('switch_host', sa.String(length=255), nullable=False),
    sa.Column('aos_version', sa.String(length=64), nullable=False),
    sa.Column('port', sa.String(length=32), nullable=False),
    sa.Column('mac', sa.String(length=12), nullable=False),
    sa.Column('vlan_id', sa.Integer(), nullable=True),
    sa.Column('vlans', sa.JSON(), nullable=False),
    sa.Column('classification', sa.String(length=16), nullable=False),
    sa.Column('classification_confidence', sa.String(length=8), nullable=False),
    sa.Column('classification_reasons', sa.JSON(), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('warnings', sa.JSON(), nullable=False),
    sa.Column('required_phrases', sa.JSON(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('execution_allowed', sa.Boolean(), nullable=False),
    sa.Column('execution_note', sa.Text(), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=False),
    sa.Column('commands', sa.JSON(), nullable=False),
    sa.Column('commands_executed', sa.JSON(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('verification', sa.JSON(), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('trunk_override', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('result_message', sa.Text(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('requested_by_id', sa.Integer(), nullable=True),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('search_id', sa.String(length=36), nullable=True),
    sa.Column('search_result_id', sa.Integer(), nullable=True),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('confirmed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], name=op.f('fk_port_actions_requested_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['switch_id'], ['switches.id'], name=op.f('fk_port_actions_switch_id_switches'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_port_actions'))
    )
    with op.batch_alter_table('port_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_port_actions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_port_actions_plan_token'), ['plan_token'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_port_actions_plan_token'))
        batch_op.drop_index(batch_op.f('ix_port_actions_created_at'))

    op.drop_table('port_actions')
    with op.batch_alter_table('mac_sightings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mac_sightings_seen_at'))
        batch_op.drop_index(batch_op.f('ix_mac_sightings_mac'))

    op.drop_table('mac_sightings')
    with op.batch_alter_table('mac_search_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mac_search_results_search_id'))

    op.drop_table('mac_search_results')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_sessions_token_hash'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('switches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_switches_name'))

    op.drop_table('switches')
    with op.batch_alter_table('mac_searches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_mac_searches_mac'))
        batch_op.drop_index(batch_op.f('ix_mac_searches_created_at'))

    op.drop_table('mac_searches')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    op.drop_table('system_settings')
    op.drop_table('strategy_approvals')
    op.drop_table('credentials')
    op.drop_table('command_profiles')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_ts'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
