"""command safety firewall

Revision ID: 0002
Revises: 0001
Create Date: 2026-09-25 20:08:06.353826
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import app.db.base


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('port_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.Column('port', sa.String(length=32), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('holder', sa.String(length=64), nullable=False),
    sa.Column('acquired_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_port_locks')),
    sa.UniqueConstraint('switch_id', 'port', name=op.f('uq_port_locks_switch_id'))
    )
    op.create_table('ssh_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=True),
    sa.Column('switch_name', sa.String(length=128), nullable=False),
    sa.Column('profile_key', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('reference', sa.String(length=64), nullable=False),
    sa.Column('operations', sa.JSON(), nullable=False),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ended_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('commands_attempted', sa.Integer(), nullable=False),
    sa.Column('commands_executed', sa.Integer(), nullable=False),
    sa.Column('commands_blocked', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('commands', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ssh_sessions'))
    )
    with op.batch_alter_table('ssh_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ssh_sessions_started_at'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ssh_sessions_switch_id'), ['switch_id'], unique=False)

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('severity', sa.String(length=8), server_default='INFO', nullable=False))
        batch_op.create_index(batch_op.f('ix_audit_logs_severity'), ['severity'], unique=False)

    with op.batch_alter_table('port_actions', schema=None) as batch_op:
        # server_default so existing rows are valid on PostgreSQL (NOT NULL on a filled table).
        batch_op.add_column(sa.Column('safety_report', sa.JSON(), nullable=False,
                                      server_default=sa.text("'{}'")))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('port_actions', schema=None) as batch_op:
        batch_op.drop_column('safety_report')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_severity'))
        batch_op.drop_column('severity')

    with op.batch_alter_table('ssh_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ssh_sessions_switch_id'))
        batch_op.drop_index(batch_op.f('ix_ssh_sessions_started_at'))

    op.drop_table('ssh_sessions')
    op.drop_table('port_locks')
    # ### end Alembic commands ###
