"""operations platform: RBAC (MAC_OPERATOR), operation modes, circuit breaker, lab
verification per model family, alerts, safety events, port snapshots, switch+port locks,
structured append-only audit.

Data migration:
* strategy_approvals → command_verifications (model_family "*": the old approvals were per AOS
  version only, so they keep applying to every supported model of the profile);
* obsolete safety settings (read_only_mode / maintenance_lock / allow_trunk_override) are
  removed; a runtime read_only_mode=true becomes operation_mode READ_ONLY;
* audit_logs becomes append-only (database triggers).

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-26 00:13:54.363062
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import json

import app.db.base
from app.db.audit_guard import create_statements, drop_statements


revision = '0003'
down_revision = '0002'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('switch_name', sa.String(length=128), nullable=False),
    sa.Column('port', sa.String(length=32), nullable=False),
    sa.Column('mac', sa.String(length=12), nullable=False),
    sa.Column('dedupe_key', sa.String(length=200), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_by', sa.String(length=64), nullable=False),
    sa.Column('acknowledged_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_kind'), ['kind'], unique=False)

    op.create_table('command_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_key', sa.String(length=32), nullable=False),
    sa.Column('capability', sa.String(length=32), nullable=False),
    sa.Column('model_family', sa.String(length=16), nullable=False),
    sa.Column('version_prefix', sa.String(length=32), nullable=False),
    sa.Column('verified_by', sa.String(length=64), nullable=False),
    sa.Column('verified_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('evidence', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_command_verifications')),
    sa.UniqueConstraint('profile_key', 'capability', 'model_family', 'version_prefix', name=op.f('uq_command_verifications_profile_key'))
    )
    op.create_table('operation_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(length=8), nullable=False),
    sa.Column('target_key', sa.String(length=64), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.Column('switch_name', sa.String(length=128), nullable=False),
    sa.Column('port', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('holder', sa.String(length=64), nullable=False),
    sa.Column('acquired_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operation_locks')),
    sa.UniqueConstraint('scope', 'target_key', name=op.f('uq_operation_locks_scope'))
    )
    op.create_table('port_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=16), nullable=False),
    sa.Column('switch_name', sa.String(length=128), nullable=False),
    sa.Column('port', sa.String(length=32), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('taken_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_port_snapshots'))
    )
    with op.batch_alter_table('port_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_port_snapshots_action_id'), ['action_id'], unique=False)

    op.create_table('safety_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ts', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('old_value', sa.String(length=64), nullable=False),
    sa.Column('new_value', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_safety_events'))
    )
    with op.batch_alter_table('safety_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_safety_events_ts'), ['ts'], unique=False)

    bind = op.get_bind()
    op.execute(
        "INSERT INTO command_verifications (profile_key, capability, model_family, "
        "version_prefix, verified_by, verified_at, notes, evidence) "
        "SELECT profile_key, strategy, '*', version_prefix, approved_by, approved_at, "
        "notes, '{\"migrated_from\": \"strategy_approvals\"}' FROM strategy_approvals"
    )
    _migrate_settings(bind)
    op.drop_table('strategy_approvals')
    op.drop_table('port_locks')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=16), server_default='', nullable=False))
        batch_op.add_column(sa.Column('operation', sa.String(length=32), server_default='', nullable=False))
        batch_op.add_column(sa.Column('vlan', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('profile', sa.String(length=32), server_default='', nullable=False))
        batch_op.add_column(sa.Column('command_fingerprint', sa.String(length=64), server_default='', nullable=False))
        batch_op.add_column(sa.Column('risk_level', sa.String(length=16), server_default='', nullable=False))
        batch_op.add_column(sa.Column('approval', sa.String(length=128), server_default='', nullable=False))
        batch_op.add_column(sa.Column('error', sa.String(length=1024), server_default='', nullable=False))
        batch_op.add_column(sa.Column('before_state', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('after_state', sa.JSON(), nullable=True))

    with op.batch_alter_table('mac_searches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mode', sa.String(length=10), server_default='STANDARD', nullable=False))

    with op.batch_alter_table('switches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=16), server_default='unknown', nullable=False))

    # ### end Alembic commands ###
    for stmt in create_statements(bind.dialect.name):
        op.execute(stmt)


def _migrate_settings(bind) -> None:
    rows = bind.execute(sa.text(
        "SELECT key, value FROM system_settings WHERE key IN "
        "('read_only_mode', 'maintenance_lock', 'maintenance_reason', 'allow_trunk_override')"
    )).all()
    values = {}
    for key, value in rows:
        if isinstance(value, str):
            try:
                value = json.loads(value)
            except ValueError:
                value = {}
        values[key] = (value or {}).get("v") if isinstance(value, dict) else None
    if values.get("read_only_mode") is True or values.get("maintenance_lock") is True:
        exists = bind.execute(sa.text(
            "SELECT 1 FROM system_settings WHERE key = 'operation_mode'")).first()
        if not exists:
            bind.execute(sa.text(
                "INSERT INTO system_settings (key, value, updated_at, updated_by) "
                "VALUES ('operation_mode', :v, CURRENT_TIMESTAMP, 'migration-0003')"),
                {"v": json.dumps({"v": "READ_ONLY"})})
    bind.execute(sa.text(
        "DELETE FROM system_settings WHERE key IN "
        "('read_only_mode', 'maintenance_lock', 'maintenance_reason', 'allow_trunk_override')"))


def downgrade() -> None:
    for stmt in drop_statements(op.get_bind().dialect.name):
        op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('switches', schema=None) as batch_op:
        batch_op.drop_column('role')

    with op.batch_alter_table('mac_searches', schema=None) as batch_op:
        batch_op.drop_column('mode')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('after_state')
        batch_op.drop_column('before_state')
        batch_op.drop_column('error')
        batch_op.drop_column('approval')
        batch_op.drop_column('risk_level')
        batch_op.drop_column('command_fingerprint')
        batch_op.drop_column('profile')
        batch_op.drop_column('vlan')
        batch_op.drop_column('operation')
        batch_op.drop_column('role')

    op.create_table('port_locks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('switch_id', sa.Integer(), nullable=False),
    sa.Column('port', sa.String(length=32), nullable=False),
    sa.Column('action_id', sa.Integer(), nullable=False),
    sa.Column('holder', sa.String(length=64), nullable=False),
    sa.Column('acquired_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_port_locks')),
    sa.UniqueConstraint('switch_id', 'port', name=op.f('uq_port_locks_switch_id'))
    )
    op.create_table('strategy_approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_key', sa.String(length=32), nullable=False),
    sa.Column('strategy', sa.String(length=32), nullable=False),
    sa.Column('version_prefix', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('approved_by', sa.String(length=64), nullable=False),
    sa.Column('approved_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_strategy_approvals')),
    sa.UniqueConstraint('profile_key', 'strategy', 'version_prefix', name=op.f('uq_strategy_approvals_profile_key'))
    )
    with op.batch_alter_table('safety_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_safety_events_ts'))

    op.drop_table('safety_events')
    with op.batch_alter_table('port_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_port_snapshots_action_id'))

    op.drop_table('port_snapshots')
    op.drop_table('operation_locks')
    op.drop_table('command_verifications')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_kind'))
        batch_op.drop_index(batch_op.f('ix_alerts_dedupe_key'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    # ### end Alembic commands ###
